layout_spectrum: 0.7449223
color:
  saturation: 1
  lightness: 0.890681
  brandStrength: 0.4928315
  brandColors:
    - '#0056C9'
    - '#61AFE7'
    - '#0A0A08'
    - '#7D6448'
    - '#E2E8F1'
  rhythmicContrast: 0.5477897
typography_spectrum: 0.8727598
name: 'Visit Hawaii '
